version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - cd codebuild_codepipeline_tf/terraform
      - terraform init
  build:
    commands:
      # TODO manual approval
      - terraform apply --auto-approve
  post_build:
    commands:
      - echo Build completed on `date`